language: php

sudo: true

addons:
  postgresql: "9.6"

services:
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

matrix:
  include:
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE NODE_VERSION=14.15.0
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE NODE_VERSION=8.16.1
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE NODE_VERSION=14.15.0
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE NODE_VERSION=14.15.0
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE NODE_VERSION=14.15.0
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_310_STABLE NODE_VERSION=14.15.0
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=master NODE_VERSION=14.15.0

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
